#### TENSORFLOW BAISC UNDERSTANDING 

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import optimizers

In [3]:
print('Version of tensorflow',tf.__version__)

Version of tensorflow 2.5.0


In [34]:
# assigning variables
print('Using tensor flow constant class to generate variable which cannot be changed')
rank_0_tensor = tf.constant(4)
print('Rank 0 tensor :',rank_0_tensor)
print('size of tensor :',rank_0_tensor.ndim)
print('size of tensor :',rank_0_tensor.shape)

Using tensor flow constant class to generate variable which cannot be changed
Rank 0 tensor : tf.Tensor(4, shape=(), dtype=int32)
size of tensor : 0
size of tensor : ()


In [38]:
y=tf.constant(7,shape=(1,1),dtype=np.float16)
print(y)
print('Rank 0 tensor :',y)
print('size of tensor :',y.ndim)
print('size of tensor :',y.shape)
print('data type of tensor :',y.dtype)

tf.Tensor([[7.]], shape=(1, 1), dtype=float16)
Rank 0 tensor : tf.Tensor([[7.]], shape=(1, 1), dtype=float16)
size of tensor : 2
size of tensor : (1, 1)
data type of tensor : <dtype: 'float16'>


In [41]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float32)
print(rank_2_tensor)
## 2nd order tensor with 32 precision

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)


In [42]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [48]:
print(rank_3_tensor.shape)
print('Along z-axis :',rank_3_tensor.shape[0])
print('No of rows :',rank_3_tensor.shape[1])
print('No of columns:',rank_3_tensor.shape[2])

(3, 2, 5)
Along z-axis : 3
No of rows : 2
No of columns: 5


In [49]:
## converting a tensor to numpy
rank_3_tensor=np.array(rank_3_tensor)
print(rank_3_tensor)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [76]:
### if your using tf.constant module to generate tensor we cannot change the values in the tensor
rnk_2=tf.Variable(rank_2_tensor)
print(rnk_2)
# to change values in tensor we use assign option in tensorflow
rnk_2[:,0].assign([7,0,2])
# Variables can be all kinds of types, just like tensors
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([[5 + 4j], [6 + 1j]],shape=(2,1))
print(complex_variable)


<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 1) dtype=complex128, numpy=
array([[5.+4.j],
       [6.+1.j]])>


### We can create random tensors by using the tf.random.Generator class.

In [77]:
## creating random tensors 
rand=tf.random.Generator.from_seed(10)
random_rank_1=rand.normal(shape=(1,3))
print(random_rank_1)

tf.Tensor([[-0.29604465 -0.21134205  0.01063002]], shape=(1, 3), dtype=float32)


In [81]:
###  random uniform data with in range
random_unifrom=rand.uniform(shape=[5,5],minval=0,maxval=-1)
print(random_unifrom)

tf.Tensor(
[[-0.41720247 -0.8913404  -0.48347986 -0.6763936  -0.8263496 ]
 [-0.32473814 -0.8825326  -0.89007044 -0.4164406  -0.12648427]
 [-0.63353837 -0.42059672 -0.65214264 -0.768108   -0.32451093]
 [-0.32453775 -0.02653694 -0.72053826 -0.6296233  -0.24667168]
 [-0.94416857 -0.4537437  -0.37142253 -0.11304879 -0.39582956]], shape=(5, 5), dtype=float32)


In [92]:
## similar to numpy tensorflow has range option with (start,stop,delta)
n_s=tf.range(0,10,1)
print(n_s.shape)
n_s=tf.reshape(n_s,[5,2])
print(n_s)

(10,)
tf.Tensor(
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]], shape=(5, 2), dtype=int32)


In [98]:
### shuffling data with tensor
shuffled_data=tf.random.shuffle(n_s)
print(n_s,shuffled_data)

tf.Tensor(
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]], shape=(5, 2), dtype=int32) tf.Tensor(
[[4 5]
 [6 7]
 [2 3]
 [8 9]
 [0 1]], shape=(5, 2), dtype=int32)


In [100]:
### other methods to generate tensors
one=tf.ones(name='ones',shape=[2,2],dtype=np.float16)
print(one)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float16)


In [102]:
zers=tf.zeros(name='zero',shape=[3,3],dtype=np.float16)
print(zers)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float16)


In [108]:
ey=tf.eye(4,dtype=np.float16)
print(ey)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float16)


In [126]:
### Higher order tensors
rank_4=tf.ones(shape=(2,3,1,4))
print(rank_4)

tf.Tensor(
[[[[1. 1. 1. 1.]]

  [[1. 1. 1. 1.]]

  [[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]

  [[1. 1. 1. 1.]]

  [[1. 1. 1. 1.]]]], shape=(2, 3, 1, 4), dtype=float32)


In [127]:
print("Datatype of every element:", rank_4.dtype)
print("Number of dimensions (rank):", rank_4.ndim)
print("Shape of tensor:", rank_4.shape)
print("Elements along axis 0 of tensor:", rank_4.shape[0])
print("Elements along last axis of tensor:", rank_4.shape[-1])
print("Total number of elements:", tf.size(rank_4).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 1, 4)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 4
Total number of elements: 24


## Tensor operations

In [156]:
## add and sub and div
a=tf.reshape(tf.range(0,10,1),shape=[5,2])
print("Boardcasting is supported")
print(a,a+10)

Boardcasting is supported
tf.Tensor(
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]], shape=(5, 2), dtype=int32) tf.Tensor(
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]], shape=(5, 2), dtype=int32)


In [163]:
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


In [164]:
b=tf.reshape(tf.range(0,10,1),shape=[5,2])
print('addition',a+b)

addition tf.Tensor(
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]], shape=(5, 2), dtype=int32)


In [165]:
print('subtraction',a-b)

subtraction tf.Tensor(
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]], shape=(5, 2), dtype=int32)


In [166]:
print('element mulmultiple ',a*b)

element mulmultiple  tf.Tensor(
[[ 0  1]
 [ 4  9]
 [16 25]
 [36 49]
 [64 81]], shape=(5, 2), dtype=int32)


In [167]:
print('element divison',a/b)

element divison tf.Tensor(
[[nan  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]], shape=(5, 2), dtype=float64)


In [168]:
c=tf.matmul(tf.transpose(a),b)
print(a.shape,b.shape)
print(c)

(5, 2) (5, 2)
tf.Tensor(
[[120 140]
 [140 165]], shape=(2, 2), dtype=int32)


In [176]:
### tensordot product 
d=tf.tensordot(tf.transpose(a),b,axes=1)
e=tf.tensordot(tf.transpose(a),b,axes=0)
print('axes= 1 is equivalent to matrix multiplication inner dot product')
print(d.shape)
print('axes=0 is equivalent to outer product')
print(e.shape)
print('number of elements',tf.size(e))

axes= 1 is equivalent to matrix multiplication inner dot product
(2, 2)
axes=0 is equivalent to outer product
(2, 5, 5, 2)
number of elements tf.Tensor(100, shape=(), dtype=int32)


In [190]:
### finding the max, min in tensor
rand=tf.random.Generator.from_seed(5)
max_A=rand.normal(shape=[3,3])
print(max_A)
print('maximum in tensor and it\'s poisiton')
print(tf.math.reduce_max(max_A))
print(tf.argmax(max_A).numpy())

tf.Tensor(
[[ 1.0278524   0.27974114 -0.01347923]
 [ 1.845181    0.97061104 -1.0242516 ]
 [-0.6544423  -0.29738766 -1.3240396 ]], shape=(3, 3), dtype=float32)
maximum in tensor and it's poisiton
tf.Tensor(1.845181, shape=(), dtype=float32)
[1 1 0]


In [195]:
rand=tf.random.Generator.from_seed(5)
uni=rand.uniform(shape=[3,3],minval=0,maxval=-1)
print(uni)
print('Absolute values of all elements in tensor')
print(tf.abs(uni))

tf.Tensor(
[[-0.567016   -0.2077086  -0.18223882]
 [-0.99883735 -0.36950588 -0.37927854]
 [-0.7723117  -0.68211746 -0.39932835]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.567016   0.2077086  0.18223882]
 [0.99883735 0.36950588 0.37927854]
 [0.7723117  0.68211746 0.39932835]], shape=(3, 3), dtype=float32)


### Squeezing a tensor (removing all single dimensions)
If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use tf.squeeze().

tf.squeeze() - remove all dimensions of 1 from a tensor

In [199]:
rank_4=tf.ones(shape=(1,1,1,4))
print(rank_4)
print(rank_4.shape)

tf.Tensor([[[[1. 1. 1. 1.]]]], shape=(1, 1, 1, 4), dtype=float32)
(1, 1, 1, 4)


In [198]:
sequeezed_ten=tf.squeeze(rank_4)
print(sequeezed_ten)
print(sequeezed_ten.shape)

tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)
(4,)


### One-hot encoding
If you have a tensor of indicies and would like to one-hot encode it, you can use tf.one_hot().

You should also specify the depth parameter (the level which you want to one-hot encode to).

In [206]:
list=[0,0,2,3,4,6,5,1]
output=tf.transpose(tf.one_hot(list,depth=6))
print(output)
print(output.shape)

tf.Tensor(
[[1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]], shape=(6, 8), dtype=float32)
(6, 8)


In [207]:
## one-hot is like pivot table, based on depth 
# the matrix is formulated if index 0's value is 5 then (0,5) is one all others values in that column are zeros

In [209]:
output=tf.transpose(tf.one_hot(list,depth=6,on_value='on',off_value='off'))
print(output)

tf.Tensor(
[[b'on' b'on' b'off' b'off' b'off' b'off' b'off' b'off']
 [b'off' b'off' b'off' b'off' b'off' b'off' b'off' b'on']
 [b'off' b'off' b'on' b'off' b'off' b'off' b'off' b'off']
 [b'off' b'off' b'off' b'on' b'off' b'off' b'off' b'off']
 [b'off' b'off' b'off' b'off' b'on' b'off' b'off' b'off']
 [b'off' b'off' b'off' b'off' b'off' b'off' b'on' b'off']], shape=(6, 8), dtype=string)


In [215]:
## performing squart and sqrt
square=tf.reshape(tf.range(0,10,1),shape=[5,2])
print(square)
print(square**2)

tf.Tensor(
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]], shape=(5, 2), dtype=int32)
tf.Tensor(
[[ 0  1]
 [ 4  9]
 [16 25]
 [36 49]
 [64 81]], shape=(5, 2), dtype=int32)


In [226]:
print(' To perform sqrt operation the data type has to be float')
sqrt=tf.cast(square,dtype=np.float16)
print(sqrt**0.5)

 To perform sqrt operation the data type has to be float
tf.Tensor(
[[0.    1.   ]
 [1.414 1.732]
 [2.    2.236]
 [2.45  2.646]
 [2.828 3.   ]], shape=(5, 2), dtype=float16)


In [231]:
square=tf.reshape(tf.range(0,10,1),shape=[5,2])
sqrt=tf.cast(square,dtype=np.float16)
ln=tf.math.log(sqrt)
print('To perform log function we need to convert datatype from int to float')
print(ln)

To perform log function we need to convert datatype from int to float
tf.Tensor(
[[  -inf 0.    ]
 [0.6934 1.099 ]
 [1.387  1.609 ]
 [1.792  1.946 ]
 [2.08   2.197 ]], shape=(5, 2), dtype=float16)


## Manipulating tf.Variable tensors
Tensors created with tf.Variable() can be changed in place using methods such as:

.assign() - assign a different value to a particular index of a variable tensor.

.add_assign() - add to an existing value and reassign it at a particular index of a variable tensor.

In [239]:
z=np.arange(0,5,1)
I=tf.Variable(z,dtype=np.float32)
print(I)

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>


In [240]:
# To change the values in the tensor variable 
I.assign([0,1,2,3,50])
print(I)

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([ 0.,  1.,  2.,  3., 50.], dtype=float32)>


### @tf.function
In the @tf.function decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with @tf.function, when you export your code (to potentially run on another device),

TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).



In [252]:
def fun(x):
    y=x**3+2*x**2+x
    return y

@tf.function
def fun_1(x):
    y=x**3+2*x**2+x
    return y

x=tf.range(0,10)
y=fun(x)
print(y)

tf.Tensor([  0   4  18  48 100 180 294 448 648 900], shape=(10,), dtype=int32)
